export const POST_BOOK  = 'POST_BOOK'
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS'
export const GET_BOOK_DETAIL = 'GET_BOOK_DETAIL'
export const EDIT_BOOK = 'EDIT_BOOK'
export const POST_NEW_USER = 'POST_NEW_USER'